# DataSource Configuration (Hardcoded with Render PostgreSQL credentials)
spring.datasource.url=jdbc:postgresql://dpg-db2a46e7bikc73d1ssh0-a/restaurant_db_72hp?sslmode=require
spring.datasource.username=restaurant_db_72hp_user
spring.datasource.password=0cMofUE7SbYx6X5WWVGbkwBlHgh7SNtL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port Configuration
server.port=${PORT:8080}